### ISSUE TITLE
Errors when Compile Sample

### ISSUE THREAD

**Issue by mitsus** [zemirco/swift-linechart#19]
Hi Zemirco,
i've a problem when try to compile your sample.
See my screen Shot
![schermata 2015-04-08 alle 23 37 34](https://cloud.githubusercontent.com/assets/5763982/7055994/71507b92-de48-11e4-9936-ecd414474f38.png)

**Comment by riccardoch** [comment]
Same problem for me!

**Comment by rakaramos** [comment]
I've same issue.
Here's what I've did to fix those:

Coordinate struct needs a 'init()' in order to fix [CGFloat] is not convertible to Range<I>.
So you'll end up with:
public struct Coordinate {
	init () {}
    // public
    public var labels: Labels = Labels()
    public var grid: Grid = Grid()
    public var axis: Axis = Axis()
    
    // private
    private var linear: LinearScale!
    private var scale: ((CGFloat) -> CGFloat)!
    private var invert: ((CGFloat) -> CGFloat)!
    private var ticks: (CGFloat, CGFloat, CGFloat)!
}

'Set' error is easier:
Change this:
override public func touchesEnded(touches: Set<NSObject>, withEvent event: UIEvent) {
With
override public func touchesEnded(touches: NSSet, withEvent event: UIEvent) {

**Comment by zemirco** [comment]
just use latest xcode

**Comment by mitsus** [comment]
Hi rakaramos,
i've follow your instructions...now i've reduce errors to two.
Please see:
![schermata 2015-04-11 alle 00 28 04](https://cloud.githubusercontent.com/assets/5763982/7098535/fdbe3796-dfe1-11e4-917e-a2e31fc6daa0.png)

**Comment by rakaramos** [comment]
mitsus,
Sorry, I've forgot to mention those last fixes.
Just change it from:
```sh
count(data)
````
to:
```sh
data.count
```
